spring.application.name=praisomart.backend

spring.datasource.url=jdbc:postgresql://localhost:5432/paisomart_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.default_schema=paisomart_auth
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=paisomart_secret_key_123456789012345678901234567890
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yaseermohamed7121@gmail.com
spring.mail.password=scwq ymfe zrbv gupo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
